### ISSUE TITLE
Change PaginatedList.getList to return a generic typed List<E> instead of a List<Object>

### ISSUE THREAD

**Issue by nzall** [hazendaz/displaytag#105]
It appears like in version 2.0 onwards, PaginatedList.getList() was changed to use List'''<Object>''' rather than a raw List without type safety. This is problematic because if someone extends this PaginatedList interface with their own generic wrapper around your raw getList, as we do, their code won't compile and instead throw warnings and errors about generic types and casting. Instead, if at all possible, PaginatedList should return a generic List<E>, allowing users with a generic wrapper around your PaginatedList to drop the use of this wrapper entirely.

Is there any particular reason why PaginatedList.getList() returns a List```<Object>``` rather than a List```<E>```?

**Comment by hazendaz** [comment]
Can you submit a pull request and with generics change can you make sure to create new list so type safety is not lost?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Please submit a pull request for any change here.

**Comment by hazendaz** [comment]
Original code actually was Object throughout and had warnings where it was not set, I'm looking at making that specific one use ```<E>``` and seeing how that impacts other portions of code specifically where internally will just treate all as List<Object> as it originally was but should allow you then to do what you want.

**Comment by hazendaz** [comment]
To add to this, 2.x line was continued from 1.2.  The original author had commits added 13 years ago called 'generics and cleanups' which changed all undefined to object internally (user fgiust).

**Comment by hazendaz** [comment]
Rather than using generics, used Row instead of Object as that is the physical object.  A test case simply extends Row and that works as well so I suspect this issue is resolved as long as caller extends Row object, therefore I'm closing this as fixed on master.  If any issue exists after next release, we can revisit.

**Comment by nzall** [comment]
I'm sorry, but we are simply unable to extend the Row object in our current setup. It's also not necessary at all right now to extend the Row object in the current implementation of the library.

**Comment by glively** [comment]
imo, it should not be List<Row>. That completely breaks the API for all existing users, and face it, 99.999% of the users of this tag are existing users looking to get rid of old deps. I have dozens and dozens of displayTag instances; there's no way I'm spending weeks re-plumbing my code to ... extend Row?. I used to be able to just set my results to the result of a JPA query and set my size. Now I cannot set my query results due to setList<List<Row>>?! I don't get it

**Comment by glively** [comment]
I should have formatted for HTML. I mean it should not return a list of Row

**Comment by hazendaz** [comment]
To add to my original comments, the original owner changed to List<Object> in 2014 per this [commit](https://github.com/hazendaz/displaytag/commit/c045f1adb37792ffca6f212ddf2bed167bdb7fc5#diff-fc275ec7470049019876a000a86104c7a00296297c0f1917115720c6f5e07355)

The actual code is a Row not Object.  This was fixed to properly reflect that in use case stated although user opted to not address it. 

Addressing that is not that complex.  If you are reading data back from a database and loading it, not understanding why you simply cannot type it nor use IDE to search/replace.  Its still a row.  Its a paginated list after all and that is what is being displayed (rows).

**Comment by glively** [comment]
First of all, thank you for your work on this project, it is much appeciated. I don't understand where I need to extend Row. I work off 'domain objects' produced by JPA queries. We have a 'custom component' that implements PaginatedList we've use for a decade or more and it's worked great. Basically the component looks like this:

```
public class DisplayTagOptions<T> implements PaginatedList {
	...
	
	@Override
	public List<T> getList() {
		return list;
	}

	public void setList(List<T> list) {
		this.list = list;
	}
	...
}
```

And a Controller that would use the above component, looks like this:

```
@GetMapping(value="/list")
public String list(...) {
	...
	DisplayTagOptions<MyObject> displayTagOptions = new DisplayTagOptions<>(...);

	displayTagOptions.setList( myService().getMyObjects(...) );
	displayTagOptions.setFullListSize(  myService().countAllMyObjects(...) );

	model.addAttribute("displayTagOptions", displayTagOptions);
	...

	return getPage("list");
}
```

And on a JSP, it would be rendered like this:

```
<display:table name="displayTagOptions" htmlId="myObjectList" uid="myObjects" id="myObject" ... >
	<display:column style="width:10%" title="ID">
		<c:out value="${myObject.id}"/>
	</display:column>
        ...
</display:table>

```

Any feedback you have is greatly appreciated. Thank you

**Comment by hazendaz** [comment]
In your example.  MyObject would extend row.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
