### ISSUE TITLE
Any chance of updating commons collections to 4.x to solve vulnerability?

### ISSUE THREAD

**Issue by void-spark** [hazendaz/displaytag#172]
Commons collections has a known vulnerability: https://issues.apache.org/jira/browse/COLLECTIONS-701
It would be nice if the latest commons collections could be used.

**Comment by hazendaz** [comment]
@void-spark That is not a vulnerability but rather a bug.  Commons collections 3.2.2 which is in display tag currently is a required transient of commons bean utils 1.9.4.  I would suggest reporting the issue to commons beanutils project.  This project also has commons collections 4 from poin at 4.4 now.

**Comment by void-spark** [comment]
It showed up as a vulnerability in security audit software, but I agree with you.
