### ISSUE TITLE
TableTag decorator init problem

### ISSUE THREAD

**Issue by SimoHi** [hazendaz/displaytag#250]
I was upgrading our project to current spring version and found this forked updated displaytag. Unfortunately seems like there is initialization error on TableTag when using column sortProperty which is method from decorator.

I compared old 1.2 version and current newest version and found that setupViewableData() on doEndTag was moved before tableDecorator.init.
![image](https://user-images.githubusercontent.com/94969767/143237404-aba56c76-1ce8-4ed5-b09a-5ac7e34cdd51.png)

Tried that decorator sorft will work with current version when that is moved after initialization.

**Comment by SimoHi** [comment]
org.displaytag.exception.RuntimeLookupException: LookupException while trying to fetch property "customSort". Cause: Error looking up property "customSort" in object type "[Ljava.lang.Object;"..
	at org.displaytag.model.RowSorter.compare(RowSorter.java:155)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at java.util.Collections.sort(Collections.java:177)
	at org.displaytag.model.TableModel.sortRowList(TableModel.java:499)
	at org.displaytag.model.TableModel.sortFullList(TableModel.java:525)
	at org.displaytag.tags.TableTag.setupViewableData(TableTag.java:1506)
	at org.displaytag.tags.TableTag.doEndTag(TableTag.java:1219)

**Comment by hazendaz** [comment]
@SimoHi Same issue was raised here https://github.com/hazendaz/displaytag/pull/72.  The code line here was pulled off work original author was doing for 2.x so this was the original authors change (break).  I can take another look to see if I can figure out the test case issues that break as a result as I don't know full history as to the change but it makes sense from initialization standpoint to go back.

**Comment by hazendaz** [comment]
@SimoHi Please build from current master and see if that solves your issues.

**Comment by SimoHi** [comment]
Seems to work now!

**Comment by hazendaz** [comment]
@SimoHi Thanks for confirming, I'm looking to try to release this weekend if I can.

**Comment by hazendaz** [comment]
closing issue as confirmed fixed in master.

**Comment by SimoHi** [comment]
Thanks for the fix! Any news of the release? :)

**Comment by hazendaz** [comment]
releasing now...
