### ISSUE TITLE
Issues migrating from displaytag 1.2 to latest version 2.4.3

### ISSUE THREAD

**Issue by rayman245** [hazendaz/displaytag#337]
Hi, I have an application which is quite old still relying on the displaytag 1.2. In the POM there are 3 dependencies that are being referenced (displaytag, displaytag-export-poi and displaytag-portlet).

After upgrading the displaytag to the latest version, the page is loaded (no errors) but empty. We have removed the old jstl library as well, that was causing another issue, but that has been fixed. Is there something we are missing out?

Reason for the upgrade is because of the commons library vulnerability issues, and we have no other option but to upgrade. Would appreciate if could guide on whats wrong.

**Comment by hazendaz** [comment]
any errors in your log file?

**Comment by rayman245** [comment]
No errors in log, are there any other ways to debug?

**Comment by hazendaz** [comment]
How about debugging your browser to see what the network shows there?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rayman245** [comment]
Closing this issue. Problem related to totally something else.
