### ISSUE TITLE
DisplayTag dows not work correctly with AjaxTags

### ISSUE THREAD

**Issue by gorbeia** [hazendaz/displaytag#4]
Hello,

I'm using displayTag in combination with AjaxTags to provide ajax behaviour to the tables. The last version of ajaxTags released in maven central (1.3-beta-rc7) does not work correctly with the latest version of displayTag. The sorting of tables is broken. AjaxTags expects the table element of displaytag to only have the "displaytag" class and the current implementation of displayTag also adds the "table" class. This prevents ajaxTags to identify the table as a candidate for link rewriting.

I have found that setting the property css.table to empty restores the sorting feature of ajaxTags.
In displaytag.properties I set:
`css.table=`

This is not a bug in displayTag but I thing it would be great to document it.

Regards

**Comment by hazendaz** [comment]
Can you add this into README and submit a pull request?

**Comment by hazendaz** [comment]
Applied via #6
