### ISSUE TITLE
Displaytag and Jakarta namespace

### ISSUE THREAD

**Issue by ArthurBorsboom** [hazendaz/displaytag#503]
In an attempt to upgrade an application from JEE8 (javax, Servlet 3.1) > JEE10 (jakarta, Servlet 5.0) the DisplayTag library version 2.5.0 results in several errors, for example

```
Failed to define class org.displaytag.tags.SetPropertyTag in Module
"deployment.flint.war" from Service Module Loader: java.lang.NoClassDefFoundError:
Failed to link org/displaytag/tags/SetPropertyTag (Module "deployment.flint.war"
from Service Module Loader): javax/servlet/jsp/tagext/BodyTagSupport
```

My assumption is that the DisplayTag library is linked to the javax namespace, while the rest of the environment is (after the upgrade) in the jakarta namespace. Many libraries have a newer versions in the jakarta namespace, for example Spring 6.

Is there an intention to migrate to the jakarta namespace?

**Comment by hazendaz** [comment]
Yes that is the ultimate intent.  The library is still on older tomcat and several tests fail when I try to upgrade it.  I've been unsuccessful on getting those working but know the code is fine up through latest tomcat 9.x.  so, I'm likely to just disable the few tests cut a release then work on jakarta.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Arthur Borsboom ***@***.***>
Sent: Tuesday, January 24, 2023 12:24:25 PM
To: hazendaz/displaytag ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hazendaz/displaytag] Displaytag and Jakarta namespace (Issue #503)


In an attempt to upgrade an application from JEE8 (javax, Servlet 3.1) > JEE10 (jakarta, Servlet 5.0) the DisplayTag library version 2.5.0 results in several errors, for example

Failed to define class org.displaytag.tags.SetPropertyTag in Module
"deployment.flint.war" from Service Module Loader: java.lang.NoClassDefFoundError:
Failed to link org/displaytag/tags/SetPropertyTag (Module "deployment.flint.war"
from Service Module Loader): javax/servlet/jsp/tagext/BodyTagSupport


My assumption is that the DisplayTag library is linked to the javax namespace, while the rest of the environment is (after the upgrade) in the jakarta namespace. Many libraries have a newer versions in the jakarta namespace, for example Spring 6.

Is there an intention to migrate to the jakarta namespace?

**Comment by ArthurBorsboom** [comment]
That is good news.

In the mean time, I have reverted to my own custom and stripped down version of DisplayTag and upgraded it to the JEE10. For my use case it seems to work. I am happy to share the source code if you are curious to see how I solved some of the issues, like thrashing certain functionalities.

The displaytag.tld needed some repetitive fixing work; it can be used as a drop-in replacement.

[displaytag.tld.txt](https://github.com/hazendaz/displaytag/files/10498592/displaytag.tld.txt)

**Comment by allantodd** [comment]
Hi,

Thanks for the project.  I hit the same problem updating an old project of mine.

I created this repo to solve our problem https://github.com/themightystags/displaytag-jakarta

Maybe the code is helpful.  I'll update to the README to advise using your version when the jakarta release is available

Thanks!

**Comment by hazendaz** [comment]
@allantodd If you want go ahead and keep that open as a PR, presumably that would eventually come in provided its all building well.  I do need to get a release out as-is then cut a backup branch then will go jakarta so it shouldn't be too long...

**Comment by allantodd** [comment]
Thanks @hazendaz .  I have raised https://github.com/hazendaz/displaytag/pull/509 .  It omits the changes on my master branch that you would not want (e.g. changes to the README and my maven coordinates).

It's mostly a simple search and replace and some updated dependencies.  I had to remove a class relating to Struts (which uses javax.servlet) and tests relating to portlets.

The tests compile but don't run owing to httpunit not supporting the jakarta.servlet package.

This version of the library works fine for me on Spring Boot 3 using the jakarta namespace

**Comment by hazendaz** [comment]
Thanks I support httpunit now too so I'll look to updating that as well.  Appreciate it!

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
Code has been merged now, release will be out within the week.  Thanks!

**Comment by hazendaz** [comment]
@ArthurBorsboom @allantodd Please see #522 as we need to consider what our baseline is.  At the moment we are claiming java 8 still because no use of release on compiler and no enforcer to ensure binary compatibility.  I believe we are at least jdk 11 but thinking we just go to 17 since most usage probably involves spring and would be pre-req.

**Comment by hazendaz** [comment]
I should add technically java 8 is still fine for EE 9 but reality is with libs updated we are more or less stating EE 10 so baseline 11.

**Comment by ArthurBorsboom** [comment]
Thanks for getting the support for Jakarta in. The application I am maintaining uses Spring 6 and thus requires Java 17 or newer. I agree that EE9 is not a serious target and we should consider EE10 as the target. So, at least Java 11 (for EE10) or Java 17 (for Spring 6 and newer).

Once the new release of Displaytag is available on Maven, I will retry to integrate it into my application and report back with the result.

Would you mind to give me a heads up if the lib has been updated in the Maven repository?
