### ISSUE TITLE
Selected sort column when media changes

### ISSUE THREAD

**Issue by TheReincarnator** [hazendaz/displaytag#544]
I found the following issue with the sorting of tables:

When then columns of a table have varying media (in my case, the first column is HTML-only, a "checkbox" column), the "defaultsort" setting, as well as the selected setting of the user, always depends on the currently selected media, not the initial (full) set of columns, so it behaves unexpectedly.

Example:

Assuming I have the following columns:
* Column 1: Checkbox, HTML only
* Colunm 2: Article number, HTML and Excel
* Column 3: Article name, HTML and Excel

I have set defaultsort="2".

When I now click on "Excel" to download an excel, it is sorted by "Article name", because the "Checkbox" column is left out.

The defaultsort, and the selected sort column, should always refer to the initial (full) set of columns.

What is the best way to fix it, I would be happy to provide a PR.

**Comment by hazendaz** [comment]
Is that zero based?  PR is ok if you know where to specifically fix if not zero based situation.

**Comment by TheReincarnator** [comment]
@hazendaz Sorry, I did not see that you replied, and we continued quite a while with a fork of displaytag:2.4.0.
Now we would like to contribute a fix to the master of your original, to be up-to-date again.
As I do not use GitHub often, I hope I did alright, creating this PR:
https://github.com/hazendaz/displaytag/pull/661
