### ISSUE TITLE
(intelliJ) displaytag.tld: "Element taglib must be declared"

### ISSUE THREAD

**Issue by N0N0** [hazendaz/displaytag#626]
I'm not really sure if this is a problem of a different JSP version of the implementing application or if it is an issue with the displaytags' taglib declaration.

But the fix to this issue was quite simple, as the taglib itself does not rely on any 2.1 specific criteria, so the fix for me was just to remove all attributes from the <taglib> element itself and adding the DOCTYPE line:

```
<!DOCTYPE taglib PUBLIC "-//Sun Microsystems, Inc.//DTD JSP Tag Library 1.2//EN" "http://java.sun.com/dtd/web-jsptaglibrary_1_2.dtd">
<taglib>

```

Thus reverting the taglib's version down to version 1.2.

**Comment by hazendaz** [comment]
Are you working off jakarta or javax namespaces?  Jakarta should be 3.0.

**Comment by N0N0** [comment]
We're working off javax, it's a very legacy application. Then the issue was with that, thanks for pointing that out!

And not to forget: displaytag (2.5.3) is working like a charme with just the little change to the tld, so thanks for that too!
