### ISSUE TITLE
Question: Is 1.2 documentation still accurate?

### ISSUE THREAD

**Issue by jsmiley208** [hazendaz/displaytag#7]
Just curious....

particularly the javadoc - http://www.displaytag.org/1.2/displaytag/apidocs/index.html

**Comment by hazendaz** [comment]
@jsmiley208 Yes the original documentation is still valid.  The original author was working towards version 2 then it seemed to become abandoned so this was carried on for a few projects needs I had.  It was completely drop in place from version 1.2 for my needs on psi-probe project and other use cases.  It intends to only support bugs and/or issues with the original line of code.  There won't be any new features added as there are many better libraries available these days (ie angular).  So this is just to keep things alive for those that are using it and cannot upgrade to anything newer and want to have something that is using the latest libraries available and is secure from any known vulnerabilities.
