### ISSUE TITLE
titleKey property not being evaluated

### ISSUE THREAD

**Issue by nrmnrm** [hazendaz/displaytag#705]
Hi,

when the element display:column contains another element (like here the "img") the titleKey is no evaluated but empty. The title attribute would work (but would be a fixed value so not useable here):

<display:column titleKey="user.status" class="realmcenter" headerClass="realmcenter"  sortable="true" >
			           			<img title="user" src="images/user_active.gif"/>
</display:column>

when it looks like this and a property like "userid" is given in the root element all is fine for titleKey:

			            <display:column property="userid" class="realmwidexxl" headerClass="realmwidexxl" titleKey="user.userid" sortable="true" />

Thanks for looking into it :)

**Comment by nrmnrm** [comment]
After some further analyzing I think we can close it, as there is a way around it. As mentioned in the commits here the struts1 support has been dropped. But thanks to https://github.com/weblegacy/struts1/ there is a supported version of struts1 using jakarta namespace now. So there are two possible solutions: Either write your own I18nStrutsAdapter and refer to it in displaytag.properties as
locale.resolver=
and
locale.provide=
(you can use code from https://sourceforge.net/p/displaytag/code/HEAD/tree/trunk/displaytag/src/main/java/org/displaytag/localization/I18nStrutsAdapter.java) and just change javax to jakarta),
Or you reintroduce I18nStrutsAdapter in the displaytag 3.0 repo, using https://sourceforge.net/p/displaytag/code/HEAD/tree/trunk/displaytag/src/main/java/org/displaytag/localization/I18nStrutsAdapter.java and doing the javax to jakarta import changes. I tested it with the weblegacy/struts1/ project, works fine for me now.

Best regards and thanks for all the hard work!

**Comment by hazendaz** [comment]
Thanks for research on that.  Will leave open for now as might use this and need to review myself.

**Comment by hazendaz** [comment]
Project now uses struts2 7.0.0 so original suggestion here would not apply if user wants struts1 as the struts2 imports where changed.  So user would need to work around if wanting such legacy support.  If you feel a lot would benefit from that please write something up on readme.md to help others with struts 1.  See commit 7a4e1aa7 for struts 2 support.

**Comment by hazendaz** [comment]
After looking at this again, I've added struts1 support back based off that as noted.  It will be in the next release.  So both struts1 and struts2 will be supported.

**Comment by hazendaz** [comment]
Thank you @nrmnrm for suggesting this.  I should have a release out today to support it as 3.1.0 release.
